package sage.gui;

import java.io.IOException;
import java.net.URL;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Represents one user or Sage message with a text avatar identifying its speaker.
 */
public class DialogBox extends HBox {
    private static final String DIALOG_BOX_FXML_PATH = "/view/DialogBox.fxml";
    private static final String USER_DIALOG_STYLE = "user-dialog";
    private static final String SAGE_DIALOG_STYLE = "sage-dialog";

    @FXML
    private Label dialog;
    @FXML
    private Label avatar;

    /**
     * Creates a message and loads its reusable FXML view.
     *
     * @param text The message shown in the dialog bubble.
     * @param speakerName The speaker name announced by accessibility tools.
     * @param avatarText The short text displayed inside the avatar.
     * @param avatarDescription The avatar description announced by accessibility tools.
     */
    private DialogBox(String text, String speakerName, String avatarText, String avatarDescription) {
        loadFxml();
        dialog.setText(text);
        dialog.setAccessibleText(speakerName + ": " + text);
        avatar.setText(avatarText);
        avatar.setAccessibleText(avatarDescription);
    }

    /**
     * Creates a right-aligned dialog for a command entered by the user.
     *
     * @param text The command entered by the user.
     * @return A dialog styled and announced as a user message.
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "You", "U", "Your avatar");
        dialogBox.getStyleClass().add(USER_DIALOG_STYLE);
        return dialogBox;
    }

    /**
     * Creates a left-aligned dialog for a response from Sage.
     *
     * @param text The response generated by Sage.
     * @return A dialog styled and announced as a Sage message.
     */
    public static DialogBox getSageDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "Sage", "S", "Sage avatar");
        dialogBox.getStyleClass().add(SAGE_DIALOG_STYLE);
        dialogBox.flip();
        return dialogBox;
    }

    /**
     * Loads this custom control by using the instance as both FXML root and controller.
     */
    private void loadFxml() {
        URL dialogBoxUrl = DialogBox.class.getResource(DIALOG_BOX_FXML_PATH);
        if (dialogBoxUrl == null) {
            throw new IllegalStateException("Missing FXML resource: " + DIALOG_BOX_FXML_PATH);
        }

        FXMLLoader fxmlLoader = new FXMLLoader(dialogBoxUrl);
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);
        try {
            fxmlLoader.load();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to load the dialog-box view.", exception);
        }
    }

    /**
     * Places the avatar on the left and the message on the right for Sage replies.
     */
    private void flip() {
        getChildren().setAll(avatar, dialog);
        setAlignment(Pos.TOP_LEFT);
    }
}
