package sage.gui;

import java.io.IOException;
import java.net.URL;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.ContextMenu;
import javafx.scene.control.Label;
import javafx.scene.control.MenuItem;
import javafx.scene.input.Clipboard;
import javafx.scene.input.ClipboardContent;
import javafx.scene.layout.HBox;

/**
 * Displays a compact user command or a full-width Sage response with an explicit status label.
 */
public class DialogBox extends HBox {
    private static final String DIALOG_BOX_FXML_PATH = "/view/DialogBox.fxml";
    private static final String USER_DIALOG_STYLE = "user-dialog";
    private static final String SAGE_DIALOG_STYLE = "sage-dialog";
    private static final String ERROR_DIALOG_STYLE = "error-dialog";

    @FXML
    private Label dialog;
    @FXML
    private Label speaker;
    @FXML
    private Label status;

    /**
     * Creates a message and loads its reusable FXML view.
     *
     * @param text The message shown in the response card or command row.
     * @param speakerName The speaker or status announced by accessibility tools.
     * @param isUserCommand Whether to use the compact command layout.
     */
    private DialogBox(String text, String speakerName, boolean isUserCommand) {
        loadFxml();
        dialog.setText(text);
        dialog.setAccessibleText(speakerName + ": " + text);
        speaker.setVisible(isUserCommand);
        speaker.setManaged(isUserCommand);
        status.setText(speakerName);
        status.setVisible(!isUserCommand);
        status.setManaged(!isUserCommand);
        addCopyMenu(text);
    }

    /**
     * Creates a compact command row with a prompt marker and distinct typography.
     *
     * @param text The command entered by the user.
     * @return A dialog styled and announced as a user message.
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "You", true);
        dialogBox.getStyleClass().add(USER_DIALOG_STYLE);
        return dialogBox;
    }

    /**
     * Creates a full-width response card that gives Sage's longer replies room to wrap.
     *
     * @param text The response generated by Sage.
     * @return A dialog styled and announced as a Sage message.
     */
    public static DialogBox getSageDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "Sage", false);
        dialogBox.getStyleClass().add(SAGE_DIALOG_STYLE);
        return dialogBox;
    }

    /**
     * Creates a response card identified as an error by both its heading and its colors.
     *
     * @param text The error and any suggested recovery steps.
     * @return An accessible error card.
     */
    public static DialogBox getErrorDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "Needs your attention", false);
        dialogBox.getStyleClass().addAll(SAGE_DIALOG_STYLE, ERROR_DIALOG_STYLE);
        return dialogBox;
    }

    /**
     * Provides a context menu for copying a command, task list, or note without its visual labels.
     *
     * @param text The complete message to copy, including line breaks.
     */
    private void addCopyMenu(String text) {
        MenuItem copyMessage = new MenuItem("Copy message");
        copyMessage.setOnAction(event -> {
            ClipboardContent content = new ClipboardContent();
            content.putString(text);
            Clipboard.getSystemClipboard().setContent(content);
        });
        dialog.setContextMenu(new ContextMenu(copyMessage));
    }

    /**
     * Loads this custom control by using the instance as both FXML root and controller.
     */
    private void loadFxml() {
        URL dialogBoxUrl = DialogBox.class.getResource(DIALOG_BOX_FXML_PATH);
        if (dialogBoxUrl == null) {
            throw new IllegalStateException("Missing FXML resource: " + DIALOG_BOX_FXML_PATH);
        }

        FXMLLoader fxmlLoader = new FXMLLoader(dialogBoxUrl);
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);
        try {
            fxmlLoader.load();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to load the dialog-box view.", exception);
        }
    }
}
