package sage;

import java.util.ArrayList;
import java.util.List;

import sage.command.Command;
import sage.core.Parser;
import sage.core.TaskList;
import sage.exception.SageException;
import sage.storage.Storage;
import sage.task.Task;
import sage.ui.Ui;

/**
 * Coordinates Sage commands for both the command-line and graphical interfaces.
 */
public class Sage {
    private final Ui ui;
    private final Storage storage;
    private final TaskList tasks;

    /**
     * Collects the output produced while processing the current graphical-interface command.
     */
    private final List<String> responseLines;

    /**
     * Routes command output to {@link #responseLines} while omitting console separators.
     */
    private final Ui responseUi;

    /**
     * Indicates whether the most recent graphical-interface command requested application exit.
     */
    private boolean isExit;

    /**
     * Describes whether the latest graphical response reports a command or persistence failure.
     */
    private boolean hasError;

    /**
     * Retains any load failure so the console and GUI can explain why saved data is unavailable.
     */
    private final String startupMessage;

    /**
     * Creates a Sage application instance backed by a data file.
     *
     * @param filePath The path where task data is stored.
     */
    public Sage(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        List<Task> loadedTasks = new ArrayList<>();
        String loadWarning = "";
        try {
            loadedTasks = storage.load();
        } catch (SageException exception) {
            loadWarning = exception.getMessage();
        }
        tasks = new TaskList(loadedTasks);
        startupMessage = loadWarning;
        responseLines = new ArrayList<>();
        responseUi = new Ui(line -> {
            if (!Ui.LINE.equals(line)) {
                responseLines.add(line);
            }
        });
        isExit = false;
    }

    /**
     * Starts the interactive command loop for the application.
     */
    public void run() {
        ui.showWelcome();
        if (!startupMessage.isEmpty()) {
            ui.showError(startupMessage);
        }
        boolean shouldExit = false;
        while (!shouldExit) {
            String fullCommand = ui.readCommand();
            if (fullCommand == null) {
                break;
            }
            boolean isListCommand = "list".equals(fullCommand.trim());
            boolean hasCommandErrored = false;
            try {
                ui.showLine();
                shouldExit = executeCommand(fullCommand, ui);
            } catch (SageException e) {
                ui.showError(e.getMessage());
                hasCommandErrored = true;
            } finally {
                if (!isListCommand && !hasCommandErrored) {
                    ui.showLine();
                }
            }
        }
    }

    /**
     * Processes a command and returns its user-facing response for a graphical interface.
     * Console separator lines are omitted from the returned response.
     *
     * @param input The command entered by the user.
     * @return The response generated by the command, without console separators.
     */
    public String getResponse(String input) {
        responseLines.clear();
        isExit = false;
        hasError = false;
        try {
            isExit = executeCommand(input, responseUi);
        } catch (SageException e) {
            hasError = true;
            responseUi.showError(e.getMessage());
        }
        return String.join(System.lineSeparator(), responseLines);
    }

    /**
     * Returns whether the most recently processed graphical-interface command exits the application.
     *
     * @return True if the most recent command was a successfully executed exit command.
     */
    public boolean isExit() {
        return isExit;
    }

    /**
     * Returns whether the latest graphical command failed, independently of the response wording.
     *
     * @return True after an invalid command or failed save; false after a successful command.
     */
    public boolean hasError() {
        return hasError;
    }

    /**
     * Returns a startup warning for display by either interface.
     *
     * @return An empty string on successful startup, or a warning about unreadable saved data.
     */
    public String getStartupMessage() {
        return startupMessage;
    }

    /**
     * Parses and executes a command using the given user interface.
     *
     * @param fullCommand The complete command entered by the user.
     * @param targetUi The user interface that receives command output.
     * @return True if the executed command requests application exit.
     * @throws SageException If the command is invalid or cannot be executed.
     */
    private boolean executeCommand(String fullCommand, Ui targetUi) throws SageException {
        Command command = Parser.parse(fullCommand);
        command.execute(tasks, targetUi, storage);
        return command.isExit();
    }

    /**
     * Runs the task manager with the default persistent data path.
     *
     * @param args Command-line arguments, currently unused.
     */
    public static void main(String[] args) {
        new Sage("data/sage.txt").run();
    }
}
